[greeter]
theme-name=Adwaita
icon-theme-name=Adwaita
font-name=Sans 12
cursor-theme-name=Adwaita
cursor-theme-size=32
background=/usr/share/backgrounds/xfce/xfce-blue.jpg
user-background=false
draw-user-backgrounds=true
show-language-selector=true
show-indicators=true
show-clock=true
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~layout;~session;~a11y;~power
position=center
default-user-image=/usr/share/pixmaps/faces/debian-logo.png
logo=/usr/share/pixmaps/debian-logo.png
screensaver-timeout=0